micronaut:
  application:
    name: example
  server:
    ssl:
      enabled: true
  ssl:
    # Let's encrypt only talks to 443 and since we are not using a load balancer or anything
    # fancy we will just do this but it will require running with `sudo` which is not idea
    # in a production environment.
    port: 443

acme:
  enabled: true
  tos-agree: true
  acme-server: https://acme-v02.api.letsencrypt.org/directory
  cert-location: /tmp
  domain: <your domain here>
  domain-key: |
    <your domain key here>
  account-key: |
    <your account key here>

