name: Java CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-acme-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-acme-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}   
    - name: Build with Gradle
      run: ./gradlew check --parallel --continue
    - name: JFrog REST API
      run: |
        curl -vvv --request PUT \
        --url https://oss.jfrog.org/artifactory/oss-snapshot-local/io/micronaut/micronaut-acme/ \
        -u ${{ secrets.BINTRAY_USER }}:${{ secrets.BINTRAY_KEY }}
    - name: Publish to JFrog OSS
      if: success() && github.event_name == 'push' && matrix.java == '8'
      env:
         BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
         BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: ./gradlew publish docs
    - name: Publish to Github Pages
      if: success() && github.event_name == 'push' && matrix.java == '8'
      uses: micronaut-projects/github-pages-deploy-action@master
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages 
        FOLDER: build/docs
